data_config:
    name: protien_graphs
    data_path: data/Enzyme
    task_type: classification
    nb_classes: 6
    nb_nodes: 1000
    split: [0.7,0.1,0.2]
    augment: 1
    fuzzy_radius: 0.25
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/enzyme_graph_new

model_config:
    model_type: gcnn
    input_shape: [1000,26,3]
    kernels_per_layer: [1]
    conv_layers: [256]
    conv_dropouts: [0.25]
    pooling_layers: [5]
    fc_layers: [128,]
    fc_dropouts: [0.5]
    nb_classes: 6
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 10
    nb_epochs: 100
    early_stop_metric: valid_loss
    save_best: True
