data_config:
    name: protien_graphs
    data_path: data/Enzyme
    task_type: classification
    nb_classes: 6
    nb_nodes: 1589
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/enzyme_graph

model_config:
    model_type: gcnn
    input_shape: [1589,25,3]
    diameter: 122.557
    conv_layers: [128,]
    conv_dropouts: [0.5,]
    pooling_factor: 5
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 6
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 100
    nb_epochs: 100
    save_best: True
