data_config:
    name: protien_graphs
    data_path: data/Enzyme
    task_type: classification
    nb_classes: 6
    nb_nodes: 1000
    split: [0.7,0.1,0.2]
    augment: 10
    fuzzy_radius: 0.15
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/enzyme_graph_new

model_config:
    model_type: gcnn
    input_shape: [1000,26,3]
    kernel_limit: 100.0
    kernels_per_layer: [4,4]
    conv_layers: [64,64]
    conv_dropouts: [0.1,0.1]
    pooling_layers: [6,6]
    fc_layers: [128,]
    fc_dropouts: [0.5]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 25
    nb_epochs: 100
    early_stop_metric: valid_loss
    early_stop_epochs: 10
    save_best: True
