data_config:
    name: protien_graphs
    data_path: data/PsiBlast
    task_type: regression
    nb_classes: 1
    nb_nodes: 170
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: scoring
    output_dir: out/krashras_graph

model_config:
    model_type: gcnn
    input_shape: [170,26,3]
    kernels_per_layer: [5,]
    conv_layers: [32,]
    conv_dropouts: [0.25,]
    pooling_layers: [1,]
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 20
    nb_epochs: 100
    early_stop_metric: valid_loss_median
    save_best: True
