data_config:
    name: protien_graphs
    data_path: data/OncoGenes
    task_type: classification
    nb_classes: 2
    nb_nodes: 447
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/oncogenes_dilated_graph

model_config:
    model_type: dilated_gcnn
    input_shape: [447,25,3]
    diameter: 500.00
    dilations: 10
    conv_layers: [256,]
    conv_dropouts: [0.5,]
    pooling_factor: 5
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 500
    nb_epochs: 100
    save_best: True
