data_config:
    name: protien_graphs
    data_path: data/PsiBlast
    task_type: classification
    nb_classes: 2
    nb_nodes: 351
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/psiblast_graph

model_config:
    model_type: gcnn
    input_shape: [351,25,3]
    diameter: 60.0
    conv_layers: [128,128]
    conv_dropouts: [0.0,0.5]
    pooling_factor: 2
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 400
    nb_epochs: 100
    save_best: True
