data_config:
    name: protien_graphs
    data_path: data/PsiBlast
    task_type: classification
    nb_classes: 2
    nb_nodes: 351
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/psiblast_graph2

model_config:
    model_type: gcnn2
    input_shape: [351,26,3]
    dilations: 5
    conv_layers: [32,]
    conv_dropouts: [0.25,]
    pooling_factor: 1
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 20
    nb_epochs: 100
    early_stop_metric: valid_acc
    save_best: True
