data_config:
    name: protien_graphs
    data_path: data/PsiBlast
    task_type: classification
    nb_classes: 2
    nb_nodes: 381
    split: [0.7,0.1,0.2]
    augment: 3
    fuzzy_radius: 0.25
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/psiblast_graph_new

model_config:
    model_type: gcnn
    input_shape: [381,29,3]
    kernel_limit: 126.0
    kernels_per_layer: [16,16]
    conv_layers: [16,16]
    conv_dropouts: [0.1,0.1]
    pooling_layers: [4,4]
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 20
    nb_epochs: 100
    early_stop_metric: valid_loss
    early_stop_epochs: 10
    save_best: True
