data_config:
    name: protien_graphs
    data_path: data/PsiBlast
    task_type: classification
    nb_classes: 2
    nb_nodes: 351
    augment: 5
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/psiblast_graph_new
    k_folds: 5
    k_fold_valid: 0.1 

model_config:
    model_type: gcnn
    input_shape: [351,26,3]
    kernels_per_layer: [5,]
    conv_layers: [32,]
    conv_dropouts: [0.25,]
    pooling_layers: [3,]
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 20
    nb_epochs: 25
    early_stop_metric: valid_loss
    early_stop_epochs: 10
    save_best: True
