data_config:
    name: protien_graphs
    data_path: data/PsiBlast
    task_type: classification
    nb_classes: 2
    nb_nodes: 351
    augment: 10
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/psiblast_graph_new2

model_config:
    model_type: gcnn
    input_shape: [351,26,3]
    kernels_per_layer: [1,] #[1,1,1,1]
    conv_layers: [64,] #[32,32,64,64]
    conv_dropouts: [0.0,] #[0.0,0.0,0.0,0.0]
    pooling_layers: [2,] #[1,1,1,1]
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 50
    nb_epochs: 100
    early_stop_metric: valid_loss
    early_stop_epochs: 10
    save_best: True
