data_config:
    name: protien_graphs
    data_path: data/PsiBlast
    task_type: classification
    nb_classes: 2
    nb_nodes: 234
    split: [0.7,0.1,0.2]
    augment: 25
    fuzzy_radius: 0.25
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/psiblast_graph_new

model_config:
    model_type: gcnn
    input_shape: [234,29,3]
    kernels_per_layer: [1,1]
    conv_layers: [32,32,]
    conv_dropouts: [0.1,0.1]
    pooling_layers: [3,3,]
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 50
    nb_epochs: 100
    early_stop_metric: valid_loss
    early_stop_epochs: 5
    save_best: True
