data_config:
    name: protien_graphs
    data_path: data/KrasHras
    task_type: classification
    nb_classes: 2
    nb_nodes: 185
    split: [0.7,0.1,0.2]
    augment: 50
    fuzzy_radius: 0.05
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/krashras_graph_new_

model_config:
    model_type: gcnn
    input_shape: [185,29,3]
    kernel_limit: 5.0
    kernels_per_layer: [4,4]
    conv_layers: [16,16]
    conv_dropouts: [0.1,0.1]
    pooling_layers: [4,4]
    fc_layers: [128,]
    fc_dropouts: [0.5]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 150
    nb_epochs: 100
    early_stop_metric: valid_loss
    early_stop_epochs: 10
    save_best: True
