data_config:
    name: protien_graphs
    data_path: data/KrasHras
    task_type: classification
    nb_classes: 2
    nb_nodes: 170
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/krashras_dilated_graph

model_config:
    model_type: dilated_gcnn
    input_shape: [170,25,3]
    diameter: 55.717
    dilations: 4
    conv_layers: [128,]
    conv_dropouts: [0.0,]
    pooling_factor: 2
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 50
    nb_epochs: 100
    save_best: True
