data_config:
    name: protien_graphs
    data_path: data/KrasHras
    task_type: classification
    nb_classes: 2
    nb_nodes: 170
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/krashras_graph

model_config:
    model_type: gcnn
    input_shape: [170,25,3]
    diameter: 200.0
    conv_layers: [128,]
    conv_dropouts: [0.5,]
    pooling_factor: 10
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 300
    nb_epochs: 100
    save_best: True
