data_config:
    name: protien_graphs
    data_path: data/KrasHras
    task_type: classification
    nb_classes: 2
    nb_nodes: 170
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/krashras_graph_new

model_config:
    model_type: gcnn
    input_shape: [170,26,3]
    kernels_per_layer: [8,]
    conv_layers: [64,]
    conv_dropouts: [0.25,]
    pooling_layers: [1,]
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 20
    nb_epochs: 100
    early_stop_metric: valid_loss
    save_best: True
