data_config:
    name: protien_graphs
    data_path: ../data/Kinase
    task_type: classification
    nb_classes: 2
    nb_nodes: 300
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: classifier
    output_dir: ../out/kinase_graph

model_config:
    model_type: gcnn
    input_shape: [300,25,3]
    diameter: 50.0 # edit
    conv_layers: [128,]
    conv_dropouts: [0.0,]
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 20
    nb_epochs: 100
    save_best: True
