data_config:
    name: protien_graphs
    data_path: data/Kinase
    task_type: classification
    nb_classes: 2
    nb_nodes: 344
    split: [0.7,0.1,0.2]
    augment: 10
    fuzzy_radius: 0.15
    seed: 1234

experiment_config:
    name: classifier
    output_dir: out/kinase_graph_new

model_config:
    model_type: gcnn
    input_shape: [344,26,3]
    kernel_limit: 73.0
    kernels_per_layer: [2,2,4,4]
    conv_layers: [64,64,128,128]
    conv_dropouts: [0.1,0.1,0.1]
    pooling_layers: [2,2,2,2]
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 50
    nb_epochs: 100
    early_stop_metric: valid_loss
    early_stop_epochs: 10
    save_best: True
