data_config:
    name: protien_graphs
    data_path: data/SARS_DEBUG
    task_type: regression
    nb_nodes: 1100
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: regressor
    output_dir: out/sars_graph

model_config:
    model_type: gcnn
    input_shape: [110,8,3]
    diameter: 20.0
    conv_layers: [128,]
    conv_dropouts: [0.0,]
    pooling_factor: 10
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 10
    nb_epochs: 100
    save_best: True
