data_config:
    name: protienligand_graphs
    data_path: data/SARS_DEBUG
    task_type: regression
    nb_nodes: 1100
    nb_classes: 1
    split: [0.7,0.1,0.2]
    seed: 1234

experiment_config:
    name: regressor
    output_dir: out/sars_graph_new

model_config:
    model_type: gcnn
    input_shape: [1100,9,3]
    kernels_per_layer: [8,]
    conv_layers: [64,]
    conv_dropouts: [0.25,]
    pooling_layers: [3,]
    fc_layers: [128,]
    fc_dropouts: [0.5,]
    nb_classes: 2
    optimizer: 'Adam'
    learning_rate: 0.0001

train_config:
    batch_size: 20
    nb_epochs: 100
    early_stop_metric: valid_loss
    early_stop_epochs: 10
    save_best: True
